import Footer from "@/components/profile-components/Footer"
import '../../globals.css'
import Header from "@/components/profile-components/Header"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
        </body>
      
    </html>
  )
}
